language: python
python:
- '2.7'
install:
- pip install .
script: nosetests
deploy:
  provider: pypi
  user: unintended
  password:
    secure: TlfCSLhKsZGglEWDspE1tO2ins9UUw2tZHXD/VkLAzQDAOltz5OTR9iRg6Fhx8ZJYiGmuWOc9ezRXnJDfzGibmQf2YH6RhrGnJs+QsMFzuvVyU9KShLy2bfNBi2qVzeoE2Wxkk34n7i+jkvQf/dqY+bggx+cvI+8lSjjppGsHhOQnXFeuMylspAee0a5hc7/KYSH2fY8x8xSNe8GNCnlekahY/ntnGviwno2KFtVtlEfa90PKGY/0o8twf/0Rk33hko7P/3GRgrZ1zV5m8yoBEjCZn5ZVu2aP1d+54hfq1UStzdh5FyIChumJRktQeXvtYHFk9zPnWebq9CB6LEI3LTXnd8nrG8Yxg5b7/tsUnY9zzMRj4ZVXejOiplAGe4H9iUePVDr9pQ/tBIvAF7XBrcmFlIrhCQ0KT5UWx0sT56rqzdmtfxXx7rx4OKaaDzWg/t6S6NtTrJ8Hn0Jdd7Ny1WL34mjvqc7qaDjCph7G4Kaah09S5jlaWAu0TfuiRD/4OyKgwmWazy87ApYH67hEEOx/Yccv8agLMtFXukphYaV36hjteoqnhh7x1S8AT5ohl4OM3eRV4RmBFU70OWLOi94BSnNAAz5RHEyUAgCknNZUnqjb0LXwCZmQNh2NVeQ7wsa912ndwGIir/qA+Lis+fXZCl819bXWdCBq4qGmZE=
  on:
    tags: true
    repo: unintended/twisted-telegram-bot
