language: python
python:
- '2.7'
install:
- pip install .
script: nosetests
deploy:
  provider: pypi
  user: unintended
  password:
    secure: fE54XzBpZJDVgnVQOWKNbK0USZce/bg+AkWGG6jQ5xMcxYLmfMZ2wtas9STWUhbbSNJGYCi0rVm80AFy6PJQLQSSqvF1T/sgHuMgD8cj4PjrGgj+y7g64kjOFoJPg6wb0ga1y5cgfWAwYd3pPFfPIx+l65wkFDpJLAU2I/5CaxpAwSYnsW+pAy5u0XowAmNmyG6pTvNWo52Hz7GJYlyCGRSAiCDaB/JeekQeMqT+SZsaKGd4TlqYDqcJH+GirR3z3IYYPOf1F8sP5w4a1b2iTOaID/Isw5kLQoV0lbDdWf/ztFgwI1syCi2tun+ebk+rUIHSRH6xet/XJTM1nh8sxiV/OPYDBN4y4xSviVCJ65oFqBG+eaR3GzVbBUtuMc8z/gGiZKa7v0c229dchTlmjXmHJMkYDwVAO/FFbLqggw1cee+ixN1bdWmKQw1X+nrVF0Bf9/5uA9ff4XrX84kohyBKghW9OYXu69V2kuFa9I2e4hCreldSimIRjZnCsmTuTdCclbAEErxcNZvOK/8QikWnreg6/7NOW4QU4dX7oSHN50gzQrwxK4l9cb3+eI52G05UkSzz2tTMKnokMJelvBWcAdsxMh9SeAJkiV8mPBaFb7uADU8gFmUYj/J010s7SDezf5/UD0l7WjNrUwBqxToUwNtfuuw37IQmuZf8pS0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: unintended/twisted-telegram-bot
